import Head from 'next/head'
import Image from 'next/image';
import Hero from '../components/Hero';
import Link from 'next/link';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Aaron Nash-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Aaron Nash' message='Aspiring web developer with a keen eye for design.'/>
      </div>
      
  );
}

      









