import Head from 'next/head'
import Image from 'next/image';
import Hero from '../components/Hero';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='JW Photography' message='I capture moments in nature that live on forever.'/>
      </div>
  );
}

      









